/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardOrgSlugIndexRouteImport } from './routes/dashboard/$orgSlug/index'
import { Route as DashboardOrgSlugTeamIdRouteImport } from './routes/dashboard/$orgSlug/$teamId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgSlugIndexRoute = DashboardOrgSlugIndexRouteImport.update({
  id: '/dashboard/$orgSlug/',
  path: '/dashboard/$orgSlug/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgSlugTeamIdRoute = DashboardOrgSlugTeamIdRouteImport.update({
  id: '/dashboard/$orgSlug/$teamId',
  path: '/dashboard/$orgSlug/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/$orgSlug/$teamId': typeof DashboardOrgSlugTeamIdRoute
  '/dashboard/$orgSlug': typeof DashboardOrgSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/$orgSlug/$teamId': typeof DashboardOrgSlugTeamIdRoute
  '/dashboard/$orgSlug': typeof DashboardOrgSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/dashboard/$orgSlug/$teamId': typeof DashboardOrgSlugTeamIdRoute
  '/dashboard/$orgSlug/': typeof DashboardOrgSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/$orgSlug/$teamId'
    | '/dashboard/$orgSlug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/api/auth/$'
    | '/dashboard/$orgSlug/$teamId'
    | '/dashboard/$orgSlug'
  id:
    | '__root__'
    | '/'
    | '/dashboard/'
    | '/api/auth/$'
    | '/dashboard/$orgSlug/$teamId'
    | '/dashboard/$orgSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  DashboardOrgSlugTeamIdRoute: typeof DashboardOrgSlugTeamIdRoute
  DashboardOrgSlugIndexRoute: typeof DashboardOrgSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgSlug/': {
      id: '/dashboard/$orgSlug/'
      path: '/dashboard/$orgSlug'
      fullPath: '/dashboard/$orgSlug'
      preLoaderRoute: typeof DashboardOrgSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/$orgSlug/$teamId': {
      id: '/dashboard/$orgSlug/$teamId'
      path: '/dashboard/$orgSlug/$teamId'
      fullPath: '/dashboard/$orgSlug/$teamId'
      preLoaderRoute: typeof DashboardOrgSlugTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  DashboardOrgSlugTeamIdRoute: DashboardOrgSlugTeamIdRoute,
  DashboardOrgSlugIndexRoute: DashboardOrgSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
